---
title: "GIS Basics in R and ArcGIS Pro"
author: "Stephanie Cunningham"
format: html
editor: visual
---

### Using R as GIS

I want to preface this by pointing out that R is not a GIS. It can handle spatial data, but there are some things that are just not as efficient as using an actual GIS, like ArcGIS Pro or QGIS.

### Packages for handing spatial data in R

There are many packages that will allow you to handle and manipulate spatial data in R. Several of these are only a few years old, and have superseded previous packages.

-   `sf` : asdfasdf
-   `terra` : Supersedes the `raster` package. Is much faster.
-   `stars` : another option for handing raster data
-   These are the heavy-hitters in my opinion, but there are several other packages that do complementary things.

This demo will use the `terra` package, as well as an extension, `tidyterra` to leverage `ggplot2`'s elegant plotting. We will also make use of the `exactextractr` package to extend some of the `terra`'s main functions.

### Types of spatial data

Vector

Raster

### How this guide is organized

Demonstrate workflow in ArcGIS

Demonstrate the same workflow in R

Note: Material for this guide was liberally borrowed from J. Frair's Landscape Ecology course (EFB ), which in turn had liberally borrowed from ...

## Using ArcGIS Pro (v. 3.3.0)

## Using R (v. 4.4.2)
